apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: test-simple
  namespace: prod-vanitydomain
spec:
  parentRefs:
    - name: traefik-gateway    
      namespace: traefik
  rules:
    - backendRefs:
        - name: vanitydomain
          port: 80
          