apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vanitydomain-tls-cert
  namespace: ${release_env}-vanitydomain 
spec:
  secretName: vanitydomain-tls
  issuerRef:
    name: letsencrypt-${release_env}
    kind: ClusterIssuer 
  dnsNames:
    - "${base_uri}"
    - "www.${base_uri}"