apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: vanitydomain-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`www.${base_uri}`) || Host(`${base_uri}`)
      kind: Rule
      services:
        - name: vanitydomain
          port: 80
      middlewares:
        - name: www-redirect
  tls:
    secretName: vanitydomain-tls

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: www-redirect
spec:
  redirectRegex:
    regex: "^https?://${base_uri}/?(.*)"
    replacement: "https://www.${base_uri}/${1}"
    permanent: true