apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: vanitydomain-routes
  namespace: ${release_env}-vanitydomain
spec:
  parentRefs:
    - name: vanitydomain-gateway
      namespace: ${release_env}-vanitydomain
      sectionName: web
    - name: vanitydomain-gateway
      namespace: ${release_env}-vanitydomain
      sectionName: https
  hostnames:
    - "${base_uri}"
    - "www.${base_uri}"
  rules:
    - backendRefs:
        - name: vanitydomain
          port: 80