apiVersion: apps/v1
kind: Deployment
metadata:
  name: vanitydomain-$(RELEASE_ENVIRONMENT)
  namespace: vanitydomain-$(RELEASE_ENVIRONMENT)
spec:
  selector:
    matchLabels:
      app: vanitydomain-$(RELEASE_ENVIRONMENT)
  replicas: 1
  template:
    metadata:
      labels:
        app: vanitydomain-$(RELEASE_ENVIRONMENT)
    spec:
      containers:
        - name: vanitydomain-$(RELEASE_ENVIRONMENT)
          image: registry.digitalocean.com/cr-cdb-sf03-dev/vanitydomain:0.0.1
