apiVersion: v1
kind: Pod
metadata:
  name: busybox-curl
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sh", "-c", "sleep 3600"]
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          cpu: "25m"
          memory: "64Mi"
        requests:
          cpu: "25m"
          memory: "64Mi"
      volumeMounts:
        - name: shared-data
          mountPath: /data
  initContainers:
    - name: init-busybox
      image: busybox
      command:
        [
          "sh",
          "-c",
          "wget -O /data/curl https://curl.se/download/curl-7.84.0.tar.gz",
        ]
      volumeMounts:
        - name: shared-data
          mountPath: /data
  volumes:
    - name: shared-data
      emptyDir: {}
