apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo-ingress
  namespace: echo
spec:
  ingressClassName: nginx
  rules:
    - host: echo1.1a4.co
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: echo1
                port:
                  number: 80
    - host: echo2.1a4.co
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: echo2
                port:
                  number: 80
    - host: echo.1a4.co
      http:
        paths:
          - pathType: Prefix
            path: /echo
            backend:
              service:
                name: echo3
                port:
                  number: 80
