apiVersion: v1
kind: Secret
metadata:
    name: ghcr-regcred
    namespace: ${release_env}-giftfeed
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:WsAmRbJYliDAok7ucr1HsCbioLPm9TZk8wEO74/EvXI7E/w0JBCIEcHaCh/fPXL3Ne4gHibHF5n2iotkczpPR64M93om/G+txRGZcKR8WFBHLxBzl5OFqurwVAYJEX2W/cVC9ywdJ+HlgkswIlCIkrtuNsjJtGDB761cT3KXitCqKIVy9fTT7Iuz3uvWiX12oBgT4WW1ADUCk4U1zTYBhkLfR45jk1ian8CZIo0P+XIKZs/iReEO/9+ie9nuOVEC0m9j4KjKo8VD/FaiI2+lajx1nvPoGNu1y8OOL/l6,iv:QEL/OXL4KgyxgvTV8Vfx6jtLY5fgZ0fRP+LE2MXqApQ=,tag:ec9nTvNNZwlhVLnEADdYOA==,type:str]
sops:
    age:
        - recipient: age1rdp8qhyu7wng3k4jte5t6yq43nqg9m5yud9p3n6gccvchh0kf4qsdkxv7w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFbnpGWWJOY1A5U1E4d3E5
            MVZrNUtoMGtxbHo1YVVMNXMwcXpBUHM1WG1RCllXem5pdnpDZEZoSEtxV215K0lx
            eTNCOGJtbGlkYUhQMStSK255MUZwYzAKLS0tIFJmMjhjWWpVMVRWZEF6czRmaFBQ
            ZnJ0ekIwbWJCcjlzd1pMVVJndjFHQ1UKYZTvfjU++f/o5578bkuFgNobjtShMlIs
            HCqI+iS34Q974SKPZSa0XBPtWtjOQO0Yis2Ei2EyXbfseC9O24kwiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T17:25:46Z"
    mac: ENC[AES256_GCM,data:5/3+g6xaZsMsYpw+VAGTPcyDaBU3Hmx6YKZYEVsb5IKtU43xrkDCkWNHXVz3ENRBW+v6QiJV8ykeiZILX4JcmpQF6LhsNSC1BTk7NW/c/1SiaX1khQG4ve3DaCaPwbBhY8wEoXMZv3CmPiU0fjmYMgmeOfuB1s99VJwLRLL4ilc=,iv:kqnRxyUvNz9DakVdqLTum9BqHDViJytRgRCfW81lEsE=,tag:leX5fr82HeVlUiRdZQCG2A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
