apiVersion: v1
kind: Secret
metadata:
    name: giftfeed-secrets
    namespace: ${release_env}-giftfeed
stringData:
    litestreamAccessKeyId: ENC[AES256_GCM,data:6jZTGgocbL/3NDKGc1WHr9SheN8=,iv:XssLsn82aq70SukD5dlzK2kjOVT2Cz1CEphH97HJQqM=,tag:8ztXDobEd8sB5tMu7vz/zg==,type:str]
    litestreamSecretAccessKey: ENC[AES256_GCM,data:6bwqRoDIPXD0IkQgUfWYAfNhaCamveVOVdHYiaPekr0M/6HzefaFJwwVNg==,iv:xJsizECziwz0rUhZChNyeiyOJfi4ytQozQf0IE6YBLY=,tag:qiZxuXNGMavDTmdb+4mX2Q==,type:str]
sops:
    age:
        - recipient: age1rdp8qhyu7wng3k4jte5t6yq43nqg9m5yud9p3n6gccvchh0kf4qsdkxv7w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5eFlmbzVadnNESnVHZVBy
            MlpZMVZIcmtFVjQzWlNvRWFEVHpWUGxyVVJFCjNHRFM0VjBHcmhQaGVCWVVrZHRz
            elAvTUNZQ3B6c0NDYVdScEFkelNXc1kKLS0tIG1ZbGw1Ym9JS3dZMVNBT1BsMEJT
            akMzRkYyNjJXSkFrSmJpOGV1cTIyWncKN6PQbq/NQKgz3dUg2naes2sdYm6qjvgX
            8+GHzfQokzapq1CJ/HeRghDkMgZ4fObbGX1CT87cOKqcDhafpD/49g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-14T17:27:59Z"
    mac: ENC[AES256_GCM,data:xgpWmIZbrV1/hPdiJwq7r6Z8sxX2NnniG0rruWUhi5ZglzTbQQ/mCs9GoFM1aSUEGiYhTT/yk0dk5Zz/1gcIOoaQ2r2uY3/YIsw8YDshenyu+OaTPjE9PRkucicPO8f2KDprZR7IrQQ2aynJBCu3HzD6L76PuR7ya5pQQ/LwnV0=,iv:adTMi2ve82A5KOt2OTBGyp81Rk8jf57FVcFf9LL/zRs=,tag:p4DYwmXpQkcLlk0rDQhPmg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
