apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 5m
  timeout: 10m0s
  chart:
    spec:
      chart: traefik
      version: '37.0.0'
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  install:
    createNamespace: true
  targetNamespace: traefik 
  values:
    resources:
      requests:
        cpu: 50m
        memory: 25Mi
      limits:
        cpu: 100m
        memory: 100Mi
    ports:
      websecure:
        tls:
          enabled: true
    providers:
      kubernetesGateway:
        enabled: true