apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: '37.0.0'
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  install:
    createNamespace: true
  targetNamespace: traefik 
  values:
    resources:
      requests:
        cpu: 50m
        memory: 10Mi
      limits:
        cpu: 100m
        memory: 50Mi