apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/vanitydomain/
namespace: ${release_env}-vanitydomain
patches:
  - path: vanitydomain.yaml
    target: 
      name: vanitydomain
      kind: Deployment
