apiVersion: apps/v1
kind: Deployment
metadata:
  name: vanitydomain
  namespace: vanitydomain
spec:
  selector:
    matchLabels:
      app: vanitydomain
  replicas: 1
  template:
    metadata:
      labels:
        app: vanitydomain
    spec:
      containers:
        - name: vanitydomain
          image: registry.digitalocean.com/cr-cdb-sf03-dev/vanitydomain:0.0.2
