apiVersion: v1
kind: Secret
metadata:
    name: config-reload-demo-secrets
    namespace: ${release_env}-config-reload-demo
stringData:
    databaseUrl: ENC[AES256_GCM,data:G0JmmpK1mHWPmvYxeL7FlvVUS3Vf0MiD3np6lJKjhpk5T9YdR9tuKg==,iv:8ioeMx3r6SFdjudPLi7YVelwlcp4b7Pm4X8K2G7Iqb4=,tag:+APWqQpl8mRHtY2nqtoIag==,type:str]
    apiKey: ENC[AES256_GCM,data:4aa8QJ1KpC1NKBheZahg8jIgVw5h3u0PyNrvqoSflH8hbZffbRWjptSO5zKgazy5yw==,iv:uO2ktvH9RpaP3K2Y0kWx8xcDOfJ1XGhIWvMzUzDf/vc=,tag:RBrN2dOIJgXyXTxHRNK+3A==,type:str]
sops:
    age:
        - recipient: age1rdp8qhyu7wng3k4jte5t6yq43nqg9m5yud9p3n6gccvchh0kf4qsdkxv7w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWQlRjRkhaWWh3ZUE0RC9k
            WWQ3MTRKL2lZaGZleWtsS2VEbHFpOGhuNmpVCm9MRUZ0T2FwY0t4Nzc2RGxhc1Qr
            NUFkWkR0SElBYjF5ZjNhSFlVL1lzSDQKLS0tIFJFc3JydTBLcm9lQVpRVWIzeFBV
            aVFLckcwZTlzYWRIeDkzTHpYTEJlejAK6mt2tqLREf6UcnrlBothnrAB3lGsZLnj
            Bpy5YWL0rccSxByowCEHglT7C7nVdCrK4yorY98cu82J20FIOk1zfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T20:09:56Z"
    mac: ENC[AES256_GCM,data:GQ9gnLpeJKT7NLmn8G7aJBHqM0ak2BuVGHHexH+wBQ7Nygf2375YWyYw8mLOU53CfS4G/Zxl9A8mQiLrB8xIZF3krdAOQo4BhX0dG9savVRuvaCw9KmYCHsKpkdQ3qyqhxmKIYkLxpsaWRE4m1zdEnjvBnteXrfwqEf4GvTRvhM=,iv:pYd24wyL6v9ATjJ+ueR458IGNUF8+UZ0V71DtHM7eJM=,tag:jplN2VT8Cd0S8gHQZhokQA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
