apiVersion: v1
kind: Secret
metadata:
    name: config-reload-demo-secrets
    namespace: ${release_env}-config-reload-demo
stringData:
    databaseUrl: ENC[AES256_GCM,data:qCOk6IKJCLgengPB2p1vDI+WTXJpOoaK+QCctZw6bqVxrDv5yw5qLA==,iv:OuA2gT5hIZL3LjE3PR6SxyAmh31m5ekdbCD9MXHPLsg=,tag:W/FrtUvVjUHC09VK+UzeDg==,type:str]
    apiKey: ENC[AES256_GCM,data:ELe5y7AudQ==,iv:DeP9b1exhSqdYLu1fGxJVfmIJ3FmMrCixLPOM1q9aZo=,tag:9/t8a9wEyskQxy/8QYzUMQ==,type:str]
sops:
    age:
        - recipient: age1rdp8qhyu7wng3k4jte5t6yq43nqg9m5yud9p3n6gccvchh0kf4qsdkxv7w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFc0RxZURKd2xUZlNJelVG
            VjBmS05ScEFqaERTZzZlR1JRZ1FReWNPV1hJCmVWWDA0VithaU9CTTJxUGN0VVR1
            aWt5U1pUTURmaCt4N0dVYlgrTlE2cnMKLS0tIDdDYUpuTHB2KzJURm0yR2wzaHo0
            L0ZjalVsNlNrODJPN1VqQVdURy8xWjAKgKJPvM1/2nnF36lngF4xGcl3rj2qVDAL
            Knh04d57eutNT/+xD/bXYZLBKqo5+gULbcbbwFQBxt9fxeWY5RserQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-20T19:06:55Z"
    mac: ENC[AES256_GCM,data:MSnQghr1Z45NCMde5ND4utQJfUicA8gESH3yRLM+4lVFJSMNpGH0KR46I2C6Ms7rXl5zDLWG1vcHbeUK4NeK6KeXHzh1YiD5x996k5hOUpw9fu+E9BoQlKCQBB9cHlLqi+X1BxKgmEvAGZ3LblyS4lZRJWZdh4eKFkX1xyiG2xY=,iv:NgUipOewVjXZd2GA0X7mURalxzzQ8myzcsmfPhEhC4k=,tag:vpKjUkVwi53GIat1AT+ytg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
