apiVersion: v1
kind: Secret
metadata:
    name: ghcr-regcred
    namespace: ${release_env}-sklonger
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:CT07PUbweJkIZXBgoVQ1PjuyO12ByOURKnouFM7HzHQhaHALr5lNpR1QUH3n6VFaH5JtZOIuWufcE7P0+IIm6AMg5uacaqF7x2UN/FOux+jG+LeXpyzW5sjWoSIEcQo1KYcnnUTQb13OXmy/mCzuOL+VerPSyKf1+/D2JeuZtlit1p8bHMbm6pOJi+PvtJhAOboP6+2U9lE0vNetkYDK3+LjHEz1mHn9IUqDKS83fTXB12j2uSZiApWw5O7dV/ZlFJxx6hbsAVpiRIYUJDHba8WRj+U6tSe8qrueFGyy,iv:GDoay6qMUl24qcit9v6RppOIff74qamzI2ias6gP4Tk=,tag:X049/tunCCM7y0E4B9O47Q==,type:str]
sops:
    age:
        - recipient: age1rdp8qhyu7wng3k4jte5t6yq43nqg9m5yud9p3n6gccvchh0kf4qsdkxv7w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxVFFVcy9ScTh0Rk5oeXZH
            WHdKbjZ3MzVIQm1lY2JJU0ZSL0ZHOXRncWtnCmlqdUdkZTI4cXNFOFp4ZGhCUFRv
            d2NBOGpNamhHU0xYUjhZTmFrdk5OKzQKLS0tIDRpY0d4Y3pNdkR3dEZCV0N0SnI0
            QXFiTFRJekU0OW9FSG05aEp2T1dMaEEKwcLjlEPYKEdZvuZdclQlIv1WEII3twbu
            +v1wjbdNgQ72k5446Ay24oAXW9OEA5F4uqTUGXVZ0qLEqA3Yh0MJsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T19:31:18Z"
    mac: ENC[AES256_GCM,data:qVbcpGSQ2RtnhbxjHNTFsg9yHUjVEq8kGG7lHr6A/iCD82FsTUTqkVwVGNfVmKxMJAd2UnSO2u1hdkn3KQklbgtyCBLONfipwx0TbqLUCcFWbEM20v+tX+W1dRZ1MK2Y/oVbUzOvwRJljHluKc2X5qLwxy5PA+WQrGSFnhvUUxE=,iv:nyKFiIo726rcyguYEt/k7r94Y3v4p4+ESBCqBMDWosM=,tag:HN3RPVRACEEaLDoYaZEy2A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
