apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - giftfeed-helmrelease.yaml
  - giftfeed-certificate.yaml
  - giftfeed-httproute.yaml
  - secrets/giftfeed-secrets.yaml
  - secrets/ghcr-regcred.yaml
