apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dev-env
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./clusters/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute:
      release_env: dev
      base_uri: dev.coryb.1a4.co


