apiVersion: v1
kind: Namespace
metadata:
  name: dev-env-infra
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: dev-repo-sync
  namespace: dev-env-infra
spec:
  interval: 1m0s
  ref:
    branch: initial-setup
  secretRef:
    name: flux-system
  url: ssh://git@github.com/coryb-xyz/k8s-cdb-sf03-dev
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: base
  namespace: dev-env-infra
spec:
  interval: 5m0s
  path: ./clusters/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: dev-repo-sync
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dev-env
  namespace: dev-env-infra
spec:
  interval: 5m0s
  path: ./clusters/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: dev-repo-sync
  postBuild:
    substitute:
      release_env: dev
      base_uri: dev.coryb.1a4.co


