apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: harbor
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./clusters/infra/harbor
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system