# clusters/infra/flux-system/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
  - metrics-server.yaml
  - prod-env-sync.yaml
  - prod-issuer.yaml


patchesStrategicMerge:
  # Kustomize controller optimization
  - |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: kustomize-controller
      namespace: flux-system
    spec:
      template:
        spec:
          containers:
          - name: manager
            resources:
              requests:
                cpu: 10m
                memory: 40Mi
              limits:
                cpu: 200m
                memory: 100Mi
            env:
            - name: GOGC
              value: "20"  # More aggressive GC
            - name: GOMEMLIMIT
              value: "90MiB"  # Override existing value

  # Source controller optimization
  - |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: source-controller
      namespace: flux-system
    spec:
      template:
        spec:
          containers:
          - name: manager
            args:
            - --helm-cache-max-size=5
            - --helm-cache-ttl=10m
            resources:
              requests:
                cpu: 10m
                memory: 30Mi
              limits:
                cpu: 200m
                memory: 80Mi

  # Helm controller optimization
  - |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: helm-controller
      namespace: flux-system
    spec:
      template:
        spec:
          containers:
          - name: manager
            resources:
              requests:
                cpu: 10m
                memory: 30Mi
              limits:
                cpu: 200m
                memory: 80Mi

  # Scale down image controllers
  - |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: image-reflector-controller
      namespace: flux-system
    spec:
      replicas: 0

  - |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: image-automation-controller
      namespace: flux-system
    spec:
      replicas: 0

  - |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: notification-controller
      namespace: flux-system
    spec:
      replicas: 0