apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml
  - metrics-server.yaml
  - prod-env-sync.yaml
  - prod-issuer.yaml

patches:
  # Optimize all main controllers' resources
  - target:
      kind: Deployment
      name: "(kustomize-controller|source-controller|helm-controller|notification-controller)"
      namespace: flux-system
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 10m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 30Mi

  # Specific higher limits for kustomize-controller
  - target:
      kind: Deployment
      name: kustomize-controller
      namespace: flux-system
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits
        value:
          cpu: 200m
          memory: 100Mi

  # Lower limits for other controllers
  - target:
      kind: Deployment
      name: "(source-controller|helm-controller)"
      namespace: flux-system
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits
        value:
          cpu: 200m
          memory: 80Mi

  # Even lower for notification controller
  - target:
      kind: Deployment
      name: notification-controller
      namespace: flux-system
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits
        value:
          cpu: 100m
          memory: 50Mi