apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: stage-env
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./clusters/stage
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute:
      release_env: sg
      base_uri: ${release_env}.coryb.1a4.co