apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor
  namespace: harbor-system
spec:
  releaseName: harbor
  chart:
    spec:
      chart: harbor
      version: '1.15.1'
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: flux-system
  interval: 1h
  install:
    createNamespace: true
  values:
    expose:
      type: ingress
      tls:
        enabled: true
    externalURL: https://cr.1a4.co
    persistence:
      enabled: true